from clases import *

#Constantes
NOMBRE_VENTANA = "Tanquesisius"
LIMITE_ANGULO_MIN = 0
LIMITE_ANGULO_MAX = 180
LIMITE_VELOCIDAD_MIN = 30
GRAVEDAD = 9.8
ANCHO_VENTANA = None
ALTO_VENTANA = None
JUGADORES = []
SALUD_JUGADOR = 100
NEGRO = (0, 0, 0)
BLANCO = (255, 255, 255)